// ajax and loading actions
export const BEGIN_AJAX_CALL = 'BEGIN_AJAX_CALL';
export const AJAX_CALL_ERROR = 'AJAX_CALL_ERROR';

// Auth actions
export const AUTH_INITIALIZATION_DONE = 'AUTH_INITIALIZATION_DONE';
export const AUTH_LOGGED_IN_SUCCESS = 'AUTH_LOGGED_IN_SUCCESS';
export const AUTH_LOGGED_OUT_SUCCESS = 'AUTH_LOGGED_OUT_SUCCESS';

// User actions
export const USER_CREATED_SUCCESS = 'USER_CREATED_SUCCESS';
export const USER_LOADED_SUCCESS = 'USER_LOADED_SUCCESS';
export const USER_IS_ADMIN_SUCCESS = 'USER_IS_ADMIN_SUCCESS';

// Chat actions
export const CHAT_ROOM_LIST_SUCCESS = 'CHAT_ROOM_LIST_SUCCESS';
export const CHAT_ROOM_CREATED_SUCCESS = 'CHAT_ROOM_CREATED_SUCCESS';
export const CHAT_ROOM_JOINED_SUCCESS = 'CHAT_ROOM_JOINED_SUCESS';
export const CHAT_ROOM_LEFT_SUCCESS = 'CHAT_ROOM_LEFT_SUCESS';
export const CHAT_ROOM_MESSAGE_SUCCESS = 'CHAT_ROOM_MESSAGE_SUCCESS';
